version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"

  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: ./compose/start
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

volumes:
  postgres_data:
