# Generated by Django 4.2.11 on 2024-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uuid_hex', models.CharField(max_length=32, unique=True)),
                ('schema', models.JSONField()),
            ],
        ),
    ]
